### ISSUE TITLE
Sesgoritma.mlmodel

### ISSUE THREAD

**Issue by mhalsamak** [ardamavi/Vocalization-Sign-Language-iOS#2]
There was a problem decoding this CoreML document
validator error: unable to deserialize object
how to use your core ml model 
when i try to use it this message show 
how to fix

**Comment by ardamavi** [comment]
Can you give detailed information about the problem? Can you try this one: https://github.com/fritzlabs/fritz-examples/issues/4#issuecomment-377942079
