### ISSUE TITLE
Not able to run this avaiable demo

### ISSUE THREAD

**Issue by manveersinghdodiya** [ardamavi/Vocalization-Sign-Language-iOS#3]
Cannot call value of non-function type 'module<Sesgoritma>'

**Comment by ardamavi** [comment]
Make sure the files are fully downloaded and located. You have to control on Xcode too.
If there is no problem in the file system, I will ask you to share detailed information about the problem.

**Comment by manveersinghdodiya** [comment]
![Screenshot 2020-01-29 at 7 01 40 PM](https://user-images.githubusercontent.com/8309190/73360909-e1a88980-42c9-11ea-9499-58d4e4af97cb.png)

**Comment by manveersinghdodiya** [comment]
i am getting this error. i am clone the repository in xcode and run the project.

**Comment by ardamavi** [comment]
Are you sure you have transferred the CoreML file correctly with drag and drop to Xcode?

**Comment by manveersinghdodiya** [comment]
me just clone the project and run it

**Comment by manveersinghdodiya** [comment]
can you please share any video or step for the configure the project

**Comment by ardamavi** [comment]
You have to drag `.mlmodel` file from downloaded repo and drop to file section that can find in left of screen in Xcode.
